# Generated by Django 5.2.4 on 2025-07-21 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0004_alter_contact_date_alter_feedback_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='questions',
            new_name='question',
        ),
    ]
