# Generated by Django 5.2.4 on 2025-07-22 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0005_rename_questions_contact_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('password', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('pic', models.FileField(default='', upload_to='user_picture')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
