# Generated by Django 5.2.4 on 2025-07-22 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0006_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=45)),
                ('profile_pic', models.FileField(default='', upload_to='user_pic/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
