# Generated by Django 5.2.4 on 2025-07-29 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0008_owner_ownerlogin_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_category', models.CharField(max_length=40)),
                ('product_description', models.TextField()),
                ('product_price', models.CharField(max_length=10)),
                ('product_pic', models.FileField(default='', upload_to='product_pic/')),
                ('product_status', models.CharField(default='available')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rent_app.owner')),
            ],
        ),
    ]
