# Generated by Django 5.2.4 on 2025-08-05 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0009_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(max_length=13)),
                ('product_id', models.CharField(max_length=10)),
                ('owner_email', models.EmailField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('returndate', models.CharField(blank=True, max_length=10, null=True)),
                ('id_proof', models.FileField(default='', upload_to='id_proof/')),
                ('product_status', models.CharField(default='rented', max_length=50)),
                ('rented_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
