# Generated by Django 5.2.4 on 2025-08-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0010_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
